"""Stubs generated by compile-evml-rote-ir."""


def translate_sales_recovery(*args, **kwargs):
    """Map Billing.PaymentDeclined to CancelOrderCommand"""
    raise NotImplementedError('translate_sales_recovery')


def decide_cancel_order(*args, **kwargs):
    """Cancel or ignore duplicate cancellation"""
    raise NotImplementedError('decide_cancel_order')


def project_cancelled_order_status(*args, **kwargs):
    """Fold OrderCancelled into CancelledOrderStatus"""
    raise NotImplementedError('project_cancelled_order_status')
