"""Stubs generated by compile-evml-rote-ir."""


def decide_place_order(*args, **kwargs):
    """Place order: inputs PlaceOrderCommand, outputs OrderPlaced or OrderPlacementRejected"""
    raise NotImplementedError('decide_place_order')


def project_order_status(*args, **kwargs):
    """Fold OrderPlaced into OrderStatus"""
    raise NotImplementedError('project_order_status')
