"""Stubs generated by compile-evml-rote-ir."""


def translate_billing(*args, **kwargs):
    """Map Sales.OrderPlaced to AuthorizePaymentCommand"""
    raise NotImplementedError('translate_billing')


def decide_authorize_payment(*args, **kwargs):
    """Authorize or decline payment"""
    raise NotImplementedError('decide_authorize_payment')


def project_payment_status(*args, **kwargs):
    """Fold PaymentAuthorized/Declined into PaymentStatus"""
    raise NotImplementedError('project_payment_status')
