"""Stubs generated by compile-evml-rote-ir."""


def translate_fulfillment(*args, **kwargs):
    """Map Billing.PaymentAuthorized to AllocateShipmentCommand"""
    raise NotImplementedError('translate_fulfillment')


def decide_allocate_shipment(*args, **kwargs):
    """Allocate or defer shipment"""
    raise NotImplementedError('decide_allocate_shipment')


def project_shipment_queue(*args, **kwargs):
    """Fold ShipmentAllocated/Deferred into ShipmentQueue"""
    raise NotImplementedError('project_shipment_queue')
